import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    emailDatabase: 'Email database',
    sendHistory: 'Send history',
    deliveryStatus: 'Delivery status',
    systemSettings: 'System settings',
    companyTools: 'COMPANY TOOLS',
    administrator: 'Administrator',
    companyAccess: 'Company access',
    searchDatabase: 'Search company email database...',
    databaseEyebrow: 'COMPANY DATABASE',
    databaseTitle: 'Email database',
    databaseSubtitle: 'Select any group of recipients and send one email to everyone with a single click.',
    importCsv: 'Import CSV',
    addEmail: 'Add email',
    companyRecipients: 'Company recipients',
    addressesAvailable: '{count} email addresses available',
    searchRecipient: 'Search name, email or company',
    recipient: 'Recipient',
    company: 'Company',
    status: 'Status',
    importTitle: 'Import the company email database',
    importHelp: 'Upload a CSV or add addresses manually. Then select recipients and send immediately.',
    selectedRecipients: '{count} recipients selected',
    readyDelivery: 'Ready for immediate delivery',
    clearSelection: 'Clear selection',
    writeSend: 'Write and send email',
    sendNow: 'Send email now',
    sendToCount: 'Send now to {count}',
    sendHelp: 'This message will be sent to {count} selected recipients.',
    to: 'TO',
    more: '+{count} more',
    subject: 'Subject',
    message: 'Message',
    messagePlaceholder: 'Write your message here...',
    individualNotice: 'One click will queue this email for all selected recipients. Each person receives an individual email.',
    cancel: 'Cancel',
    sending: 'Sending...',
    addDatabaseTitle: 'Add email to database',
    fullName: 'Full name',
    emailAddress: 'Email address',
    tags: 'Tags',
    tagsPlaceholder: 'client, partner, team',
    addDatabase: 'Add email',
    emailAdded: 'Email added to the database',
    imported: 'Imported {imported} of {total} email addresses',
    queued: 'Email queued for {count} recipients',
    historyTitle: 'Send history',
    historySubtitle: 'Review messages sent from the company email database.',
    sendEmailNow: 'Send email now',
    last30: 'Last 30 days',
    last7: 'Last 7 days',
    last3Weeks: 'Last 3 weeks',
    last90: 'Last 90 days',
    lastYear: 'Last year',
    allTime: 'All time',
    recentSends: 'Recent sends',
    staffMessages: 'Messages sent by company staff.',
    noEmails: 'No company emails sent yet',
    selectRecipients: 'Select recipients',
    systemStatus: 'System status',
    operational: 'System operational',
    openDatabase: 'Open email database',
    deliveryTitle: 'Delivery status',
    deliverySubtitle: 'Follow every delivery job and resolve failures quickly.',
    refresh: 'Refresh',
    waiting: 'Waiting',
    sendingNow: 'Sending now',
    delivered: 'Delivered',
    failed: 'Failed',
    deliveryProgress: 'Delivery progress',
    clearFailed: 'Clear failed',
    retryFailed: 'Retry failed',
    queueReady: 'The queue is ready',
    queueReadyHelp: 'Email jobs will appear here after you send a message.',
    settingsTitle: 'System settings',
    settingsSubtitle: 'Configure the company sender and email delivery provider.',
    saveSettings: 'Save settings',
    senderIdentity: 'Sender identity',
    senderHelp: 'What clients see in their inbox.',
    senderName: 'Sender name',
    senderEmail: 'Sender email',
    emailProvider: 'Email provider',
    providerHelp: 'Choose how company emails are delivered.',
    deliveryMethod: 'Delivery method',
    previewMode: 'Preview mode (no real emails)',
    smtpServer: 'Company SMTP server',
    sendgrid: 'SendGrid',
    smtpHost: 'SMTP host',
    port: 'Port',
    username: 'Username',
    password: 'Password',
    secureTls: 'Use secure TLS connection',
    apiKey: 'SendGrid API key',
    testConnection: 'Test connection',
    previewInfo: 'Safe testing mode is active. Messages are processed but not delivered externally.',
    storedLocally: 'Configuration is stored locally',
    storedHelp: 'Changes apply immediately to future email sends.',
    simpleSettingsHelp: 'Connect the company email and send a quick test message.',
    emailConnection: 'Email connection',
    emailConnectionHelp: 'Choose Gmail or Outlook. Technical settings are automatic.',
    companyEmail: 'Company email',
    appPassword: 'App password',
    appPasswordHelp: 'Use an app password generated by Gmail or Microsoft, not your normal password.',
    testEmailTitle: 'Send a test email',
    testEmailHelp: 'Enter your own address to verify how delivery works.',
    testRecipient: 'Test recipient email',
    sendTestEmail: 'Send test email',
    settingsSaved: 'Settings saved',
    settingsLoadError: 'Could not load settings',
    settingsSaveError: 'Could not save settings',
    previewTestDone: 'Test processed in preview mode. No real email was delivered.',
    testEmailSent: 'Test email sent successfully',
    testEmailFailed: 'Test email could not be sent'
    ,composeTitle: 'Compose email'
    ,composeSubtitle: 'Choose clients, write the message and attach photos or documents.'
    ,chooseRecipients: 'Choose clients'
    ,writeMessage: 'Write message'
    ,attachments: 'Attachments'
    ,attachmentsHelp: 'Up to 5 files, maximum 10 MB each.'
    ,addPhoto: 'Add photo'
    ,addFile: 'Add file'
    ,noRecipients: 'Add clients to the database first.'
    ,fileTooLarge: 'A file is larger than 10 MB.'
    ,loadRecipientsError: 'Could not load clients.'
    ,sendFailed: 'Email could not be sent.'
    ,previewSendBlocked: 'Real delivery is not configured. Connect Gmail or Outlook before sending.'
    ,configureEmail: 'Configure email'
  },
  ro: {
    emailDatabase: 'Baza de emailuri', sendHistory: 'Istoric trimiteri', deliveryStatus: 'Starea livrărilor', systemSettings: 'Setări sistem',
    companyTools: 'INSTRUMENTE COMPANIE', administrator: 'Administrator', companyAccess: 'Acces companie', searchDatabase: 'Caută în baza de emailuri...',
    databaseEyebrow: 'BAZA COMPANIEI', databaseTitle: 'Baza de emailuri', databaseSubtitle: 'Selectează clienții și trimite același email tuturor cu un singur click.',
    importCsv: 'Importă CSV', addEmail: 'Adaugă email', companyRecipients: 'Clienții companiei', addressesAvailable: '{count} adrese de email disponibile',
    searchRecipient: 'Caută nume, email sau companie', recipient: 'Client', company: 'Companie', status: 'Stare',
    importTitle: 'Importă baza de emailuri a companiei', importHelp: 'Încarcă un CSV sau adaugă adrese manual. Apoi selectează clienții și trimite imediat.',
    selectedRecipients: '{count} clienți selectați', readyDelivery: 'Pregătit pentru trimitere imediată', clearSelection: 'Șterge selecția', writeSend: 'Scrie și trimite email',
    sendNow: 'Trimite email acum', sendToCount: 'Trimite acum la {count}', sendHelp: 'Mesajul va fi trimis celor {count} clienți selectați.',
    to: 'CĂTRE', more: '+încă {count}', subject: 'Subiect', message: 'Mesaj', messagePlaceholder: 'Scrie mesajul aici...',
    individualNotice: 'Cu un singur click, emailul este trimis tuturor clienților selectați. Fiecare primește un email individual.',
    cancel: 'Anulează', sending: 'Se trimite...', addDatabaseTitle: 'Adaugă email în bază', fullName: 'Nume complet', emailAddress: 'Adresă email',
    tags: 'Etichete', tagsPlaceholder: 'client, partener, echipă', addDatabase: 'Adaugă email', emailAdded: 'Email adăugat în bază',
    imported: 'Au fost importate {imported} din {total} adrese', queued: 'Email pregătit pentru {count} clienți',
    historyTitle: 'Istoric trimiteri', historySubtitle: 'Vezi mesajele trimise din baza companiei.', sendEmailNow: 'Trimite email acum', last30: 'Ultimele 30 zile',
    last7: 'Ultimele 7 zile', last3Weeks: 'Ultimele 3 săptămâni', last90: 'Ultimele 90 zile', lastYear: 'Ultimul an', allTime: 'Tot timpul',
    recentSends: 'Trimiteri recente', staffMessages: 'Mesaje trimise de angajații companiei.', noEmails: 'Nu a fost trimis niciun email', selectRecipients: 'Selectează clienții',
    systemStatus: 'Starea sistemului', operational: 'Sistem funcțional', openDatabase: 'Deschide baza de emailuri',
    deliveryTitle: 'Starea livrărilor', deliverySubtitle: 'Urmărește trimiterile și rezolvă erorile.', refresh: 'Actualizează', waiting: 'În așteptare',
    sendingNow: 'Se trimit', delivered: 'Livrate', failed: 'Eșuate', deliveryProgress: 'Progres livrare', clearFailed: 'Șterge eșuate',
    retryFailed: 'Reîncearcă', queueReady: 'Coada este pregătită', queueReadyHelp: 'Trimiterile vor apărea aici după expedierea unui mesaj.',
    settingsTitle: 'Setări sistem', settingsSubtitle: 'Configurează expeditorul și serviciul de trimitere al companiei.', saveSettings: 'Salvează setările',
    senderIdentity: 'Identitatea expeditorului', senderHelp: 'Ce văd clienții în inbox.', senderName: 'Numele expeditorului', senderEmail: 'Emailul expeditorului',
    emailProvider: 'Serviciu email', providerHelp: 'Alege cum sunt livrate emailurile companiei.', deliveryMethod: 'Metoda de livrare',
    previewMode: 'Mod test (fără emailuri reale)', smtpServer: 'Server SMTP companie', sendgrid: 'SendGrid', smtpHost: 'Gazdă SMTP', port: 'Port',
    username: 'Utilizator', password: 'Parolă', secureTls: 'Folosește conexiune TLS securizată', apiKey: 'Cheie API SendGrid',
    testConnection: 'Testează conexiunea', previewInfo: 'Modul sigur de test este activ. Mesajele nu sunt livrate extern.',
    storedLocally: 'Configurația este salvată local', storedHelp: 'Modificările se aplică imediat trimiterilor viitoare.',
    simpleSettingsHelp: 'Conectează emailul companiei și trimite rapid un mesaj de probă.',
    emailConnection: 'Conectare email', emailConnectionHelp: 'Alege Gmail sau Outlook. Setările tehnice sunt automate.',
    companyEmail: 'Emailul companiei', appPassword: 'Parolă de aplicație',
    appPasswordHelp: 'Folosește parola de aplicație generată de Gmail sau Microsoft, nu parola normală.',
    testEmailTitle: 'Trimite un email de probă', testEmailHelp: 'Introdu adresa ta pentru a verifica trimiterea.',
    testRecipient: 'Email destinatar de probă', sendTestEmail: 'Trimite email de probă',
    settingsSaved: 'Setările au fost salvate', settingsLoadError: 'Setările nu au putut fi încărcate',
    settingsSaveError: 'Setările nu au putut fi salvate', previewTestDone: 'Test procesat în modul de probă. Nu a fost livrat un email real.',
    testEmailSent: 'Emailul de probă a fost trimis', testEmailFailed: 'Emailul de probă nu a putut fi trimis'
    ,composeTitle: 'Compune email'
    ,composeSubtitle: 'Alege clienții, scrie mesajul și atașează fotografii sau documente.'
    ,chooseRecipients: 'Alege clienții'
    ,writeMessage: 'Scrie mesajul'
    ,attachments: 'Atașamente'
    ,attachmentsHelp: 'Maximum 5 fișiere, câte 10 MB fiecare.'
    ,addPhoto: 'Adaugă fotografie'
    ,addFile: 'Adaugă fișier'
    ,noRecipients: 'Adaugă mai întâi clienți în baza de date.'
    ,fileTooLarge: 'Un fișier depășește 10 MB.'
    ,loadRecipientsError: 'Clienții nu au putut fi încărcați.'
    ,sendFailed: 'Emailul nu a putut fi trimis.'
    ,previewSendBlocked: 'Trimiterea reală nu este configurată. Conectează Gmail sau Outlook înainte de expediere.'
    ,configureEmail: 'Configurează emailul'
  },
  ru: {
    emailDatabase: 'База email', sendHistory: 'История отправок', deliveryStatus: 'Статус доставки', systemSettings: 'Настройки системы',
    companyTools: 'ИНСТРУМЕНТЫ КОМПАНИИ', administrator: 'Администратор', companyAccess: 'Доступ компании', searchDatabase: 'Поиск в базе email...',
    databaseEyebrow: 'БАЗА КОМПАНИИ', databaseTitle: 'База email', databaseSubtitle: 'Выберите клиентов и отправьте одно сообщение всем одним нажатием.',
    importCsv: 'Импорт CSV', addEmail: 'Добавить email', companyRecipients: 'Клиенты компании', addressesAvailable: 'Доступно адресов: {count}',
    searchRecipient: 'Поиск по имени, email или компании', recipient: 'Клиент', company: 'Компания', status: 'Статус',
    importTitle: 'Импорт базы email компании', importHelp: 'Загрузите CSV или добавьте адреса вручную. Затем выберите клиентов и отправьте сообщение.',
    selectedRecipients: 'Выбрано клиентов: {count}', readyDelivery: 'Готово к немедленной отправке', clearSelection: 'Очистить выбор', writeSend: 'Написать и отправить',
    sendNow: 'Отправить сейчас', sendToCount: 'Отправить для {count}', sendHelp: 'Сообщение будет отправлено выбранным клиентам: {count}.',
    to: 'КОМУ', more: '+ещё {count}', subject: 'Тема', message: 'Сообщение', messagePlaceholder: 'Напишите сообщение...',
    individualNotice: 'Одним нажатием письмо будет отправлено всем выбранным клиентам. Каждый получит отдельное письмо.',
    cancel: 'Отмена', sending: 'Отправка...', addDatabaseTitle: 'Добавить email в базу', fullName: 'Полное имя', emailAddress: 'Email адрес',
    tags: 'Метки', tagsPlaceholder: 'клиент, партнёр, команда', addDatabase: 'Добавить email', emailAdded: 'Email добавлен в базу',
    imported: 'Импортировано {imported} из {total} адресов', queued: 'Письмо подготовлено для {count} клиентов',
    historyTitle: 'История отправок', historySubtitle: 'Просмотр сообщений, отправленных из базы компании.', sendEmailNow: 'Отправить email', last30: 'Последние 30 дней',
    last7: 'Последние 7 дней', last3Weeks: 'Последние 3 недели', last90: 'Последние 90 дней', lastYear: 'Последний год', allTime: 'За всё время',
    recentSends: 'Последние отправки', staffMessages: 'Сообщения сотрудников компании.', noEmails: 'Письма ещё не отправлялись', selectRecipients: 'Выбрать клиентов',
    systemStatus: 'Статус системы', operational: 'Система работает', openDatabase: 'Открыть базу email',
    deliveryTitle: 'Статус доставки', deliverySubtitle: 'Контролируйте отправки и исправляйте ошибки.', refresh: 'Обновить', waiting: 'Ожидают',
    sendingNow: 'Отправляются', delivered: 'Доставлены', failed: 'Ошибки', deliveryProgress: 'Прогресс доставки', clearFailed: 'Очистить ошибки',
    retryFailed: 'Повторить', queueReady: 'Очередь готова', queueReadyHelp: 'Отправки появятся здесь после отправки сообщения.',
    settingsTitle: 'Настройки системы', settingsSubtitle: 'Настройте отправителя и сервис доставки компании.', saveSettings: 'Сохранить',
    senderIdentity: 'Данные отправителя', senderHelp: 'Что клиенты увидят во входящих.', senderName: 'Имя отправителя', senderEmail: 'Email отправителя',
    emailProvider: 'Почтовый сервис', providerHelp: 'Выберите способ доставки писем.', deliveryMethod: 'Способ доставки',
    previewMode: 'Тестовый режим (без реальных писем)', smtpServer: 'SMTP сервер компании', sendgrid: 'SendGrid', smtpHost: 'SMTP сервер', port: 'Порт',
    username: 'Пользователь', password: 'Пароль', secureTls: 'Использовать защищённое TLS соединение', apiKey: 'API ключ SendGrid',
    testConnection: 'Проверить соединение', previewInfo: 'Безопасный тестовый режим активен. Письма не отправляются наружу.',
    storedLocally: 'Настройки сохранены локально', storedHelp: 'Изменения сразу применяются к будущим отправкам.',
    simpleSettingsHelp: 'Подключите почту компании и отправьте тестовое сообщение.',
    emailConnection: 'Подключение почты', emailConnectionHelp: 'Выберите Gmail или Outlook. Технические настройки автоматические.',
    companyEmail: 'Email компании', appPassword: 'Пароль приложения',
    appPasswordHelp: 'Используйте пароль приложения Gmail или Microsoft, а не обычный пароль.',
    testEmailTitle: 'Отправить тестовое письмо', testEmailHelp: 'Введите свой адрес, чтобы проверить отправку.',
    testRecipient: 'Тестовый email получателя', sendTestEmail: 'Отправить тест',
    settingsSaved: 'Настройки сохранены', settingsLoadError: 'Не удалось загрузить настройки',
    settingsSaveError: 'Не удалось сохранить настройки', previewTestDone: 'Тест обработан в пробном режиме. Реальное письмо не доставлено.',
    testEmailSent: 'Тестовое письмо отправлено', testEmailFailed: 'Не удалось отправить тестовое письмо'
    ,composeTitle: 'Создать письмо'
    ,composeSubtitle: 'Выберите клиентов, напишите сообщение и прикрепите фото или документы.'
    ,chooseRecipients: 'Выберите клиентов'
    ,writeMessage: 'Напишите сообщение'
    ,attachments: 'Вложения'
    ,attachmentsHelp: 'До 5 файлов, максимум 10 МБ каждый.'
    ,addPhoto: 'Добавить фото'
    ,addFile: 'Добавить файл'
    ,noRecipients: 'Сначала добавьте клиентов в базу.'
    ,fileTooLarge: 'Размер файла превышает 10 МБ.'
    ,loadRecipientsError: 'Не удалось загрузить клиентов.'
    ,sendFailed: 'Не удалось отправить письмо.'
    ,previewSendBlocked: 'Реальная отправка не настроена. Подключите Gmail или Outlook.'
    ,configureEmail: 'Настроить почту'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('mailCenterLanguage') || 'ro');
  const value = useMemo(() => ({
    language,
    setLanguage: (next) => {
      localStorage.setItem('mailCenterLanguage', next);
      setLanguage(next);
    },
    t: (key, params = {}) => {
      let text = translations[language]?.[key] || translations.en[key] || key;
      Object.entries(params).forEach(([name, value]) => {
        text = text.replaceAll(`{${name}}`, value);
      });
      return text;
    }
  }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
